/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_adapter_gpio.h"
#include "pin_mux.h"
#include "fsl_gpt.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN GPIO5_Combined_0_15_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER GPIO5_Combined_0_15_IRQHandler
/* gpio_io, 00 signal defines */
/* Definition of the pin direction */
#define BOARD_INITPINS_USER_BUTTON_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITPINS_USER_BUTTON_PIN_LEVEL 0U
/* Definition of the pin trigger mode */
#define BOARD_INITPINS_USER_BUTTON_TRIGGER_MODE kHAL_GpioInterruptFallingEdge
/* Definition of peripheral ID */
#define GPT2_PERIPHERAL GPT2
/* Definition of the clock source frequency */
#define GPT2_CLOCK_SOURCE 75000000UL
/* GPT2 interrupt vector ID (number). */
#define GPT2_GPT_IRQN GPT2_IRQn
/* GPT2 interrupt vector priority. */
#define GPT2_GPT_IRQ_PRIORITY 2
/* GPT2 interrupt handler identifier. */
#define GPT2_GPT_IRQHANDLER GPT2_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern GPIO_HANDLE_DEFINE(BOARD_INITPINS_USER_BUTTON_handle);
extern const gpt_config_t GPT2_config;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level);

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* Callback function for the BOARD_INITPINS_USER_BUTTON_handle*/
extern void BOARD_INITPINS_USER_BUTTON_callback(void *param);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
